script: ./gradlew -s clean assembleDebug
language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - android-19
    - sysimg-19
    - extra-android-m2repository

