import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val recyclerview_v7: String = "com.android.support:recyclerview-v7:" +
            Versions.com_android_support

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val support_v4: String = "com.android.support:support-v4:" + Versions.com_android_support

    /**
     * https://developer.android.com/studio */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" +
            Versions.com_gradle_build_scan_gradle_plugin

    /**
     * https://github.com/koush/UrlImageViewHelper */
    const val urlimageviewhelper: String =
            "com.koushikdutta.urlimageviewhelper:urlimageviewhelper:" + Versions.urlimageviewhelper

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/groovy/groovy-android-gradle-plugin */
    const val gradle_groovy_android_plugin: String =
            "org.codehaus.groovy:gradle-groovy-android-plugin:" +
            Versions.gradle_groovy_android_plugin

    /**
     * http://groovy-lang.org */
    const val groovy_json: String = "org.codehaus.groovy:groovy-json:" + Versions.groovy_json

    /**
     * http://groovy-lang.org */
    const val groovy: String = "org.codehaus.groovy:groovy:" + Versions.groovy
}
